name: hdp_deliveries
description: "A Flutter project for delivery management in the HDP Business Suite."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_fonts: ^7.0.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  go_router: ^17.0.1
  url_launcher: ^6.3.1 # For opening maps
  shared_preferences: ^2.5.4
  flutter_map: ^6.1.0 # OpenStreetMap integration
  latlong2: ^0.9.0 # Coordinate handling
  http: ^1.2.0 # For OSRM routing API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"


flutter:
  uses-material-design: true
